"""
DIGIFORMATION LTD — Lead Hunter
Phase 02: Verification Engine (Identity, Website, WhatsApp & Shariah Compliance)
"""
import os
import re
from datetime import datetime
from typing import Dict, Any, Tuple, List

from services.website_analyzer import WebsiteAnalyzer
from services.web_presence import research_presence


class VerificationService:
    def __init__(self):
        self.website_analyzer = WebsiteAnalyzer()

    def verify_candidate(self, candidate: Dict[str, Any]) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        evidence_list = []
        now_str = datetime.now().isoformat()

        # Live web-presence check — the step that turns a raw OSM record into an
        # HONEST lead. OSM rarely records a website and never proves a phone has
        # WhatsApp, so without this the pipeline emits "no website" / "WhatsApp"
        # leads that are simply wrong. This actively searches the web for the
        # business's OWN website and advertised WhatsApp. It runs only when the
        # batch supplies a city hint (candidate["_city"]); unit tests that call
        # verify_candidate directly skip the network and get the OSM-only path.
        presence = None
        if candidate.get("_city") and os.environ.get("LEADHUNTER_LIVE_VERIFY", "1") != "0":
            try:
                presence = research_presence(
                    candidate.get("business_name", ""),
                    candidate.get("_city", ""),
                    candidate.get("_country", ""),
                    candidate.get("phone", ""),
                )
            except Exception:
                presence = None

        # 1. Identity Verification
        evidence_list.append({
            "claim": "Business Name Matches Source Record",
            "value": candidate["business_name"],
            "evidence_level": "E1_DIRECT",
            "source": candidate.get("source", "OpenStreetMap (Overpass API) public open data"),
            "source_url": candidate.get("google_maps_url"),
            "observed_at": now_str,
            "notes": (
                f"A record named '{candidate['business_name']}' was returned for "
                f"{candidate.get('location')} / {candidate.get('category')}. This confirms the "
                f"upstream dataset holds a matching entry; it does NOT independently confirm "
                f"that the business currently trades at this location."
            )
        })

        # 1b. Discovery Provenance — must be explicit so demo records can never be
        # mistaken for live external results. The wording is derived from the actual
        # provenance value: labelling a machine-generated demo record as coming from
        # the "seed dataset" would itself be a false statement about its origin.
        provenance = candidate.get("data_provenance", "LIVE_EXTERNAL_SOURCE")
        if provenance != "LIVE_EXTERNAL_SOURCE":
            if provenance == "SYNTHETIC_DEMO_RECORD":
                provenance_value = "SYNTHETIC DEMO RECORD — MACHINE-GENERATED, NOT A REAL BUSINESS"
                provenance_notes = (
                    "This record was generated by an earlier build of this tool to exercise the "
                    "pipeline. No external source was queried for it. Its name, address, phone "
                    "number and any figures it once carried were synthesised, and its original "
                    "evidence log cited a WhatsApp validator that was never implemented. It must "
                    "not be contacted and must not appear in outreach."
                )
            else:
                provenance_value = "SAMPLE / SEED DATASET — NOT LIVE-VERIFIED"
                provenance_notes = (
                    "This lead came from the application's pre-loaded sample dataset, not from a "
                    "live OpenStreetMap/Google query performed during this run. Its name, address "
                    "and phone number were bundled with the software and were NOT re-checked "
                    "against any external source at run time. Treat it as a demo record."
                )
            evidence_list.append({
                "claim": "Discovery Data Provenance",
                "value": provenance_value,
                "evidence_level": "E0_UNVERIFIED",
                "source": candidate.get("source", "Bundled sample reference record"),
                "source_url": None,
                "observed_at": now_str,
                "notes": provenance_notes
            })

        # 2. Shariah Compliance Verification
        evidence_list.append({
            "claim": "Automated Prohibited-Keyword Screen",
            "value": "NO PROHIBITED KEYWORDS DETECTED",
            "evidence_level": "E3_INFERRED",
            "source": "DIGIFORMATION LTD keyword blocklist screen",
            "source_url": None,
            "observed_at": now_str,
            "notes": (
                "The business name, category and description were scanned against a keyword "
                "blocklist for interest (riba), gambling, intoxicants and prohibited trade, and "
                "no match was found. This is a TEXT SCREEN, not a halal certification or an "
                "audit of actual ingredients, sourcing or handling."
            )
        })

        # 3. Website Verification (with real fetch + evidence)
        raw_web = candidate.get("website_url", "")
        website_status = "NO_WEBSITE"
        website_audit = {}
        website_analysis = None

        is_social_only = bool(raw_web and any(soc in raw_web.lower() for soc in ["facebook.com", "instagram.com", "tiktok.com", "wa.me", "whatsapp.com", "foodpanda.pk"]))

        if not raw_web or raw_web.strip() == "" or "none" in raw_web.lower() or is_social_only:
            website_status = "NO_WEBSITE"
            social_note = f" (Social media profile found: {raw_web})" if is_social_only else ""

            # The OSM record lists no website. Before declaring this a greenfield
            # "no website" opportunity, actively SEARCH the web — the single most
            # important fix against false "no website" leads.
            if presence is not None and presence.get("website_found"):
                # A real official site was found online. This is NOT a no-website
                # lead; record the site so classification treats it as "has site".
                website_status = "LIVE"
                website_audit = {"found_via": "web_search", "url": presence["website_found"]}
                evidence_list.append({
                    "claim": "Official Website Status",
                    "value": f"WEBSITE_FOUND ({presence['website_found']})",
                    "evidence_level": "E2_STRONG",
                    "source": "Live web search (Bing)",
                    "source_url": presence["website_found"],
                    "observed_at": now_str,
                    "notes": (
                        f"OSM listed no website, but a live web search found an official site: "
                        f"{presence['website_found']}. This business already has a web presence, "
                        f"so it is NOT a build-ready 'no website' lead."
                    ),
                })
            elif presence is not None and presence.get("searched"):
                # A real search ran and found no official site -> genuinely no website.
                evidence_list.append({
                    "claim": "Official Website Status",
                    "value": "NO_WEBSITE",
                    "evidence_level": "E2_STRONG",
                    "source": "Live web search (Bing)",
                    "source_url": (presence.get("sources") or [None])[0],
                    "observed_at": now_str,
                    "notes": (
                        f"No website in OSM{social_note}, AND a live web search for "
                        f"'{candidate.get('business_name','')}' returned no official site. "
                        f"Confirmed no-website lead (searched, none found)."
                    ),
                })
            else:
                # No OSM website and the live search could not run (blocked/offline).
                # Do NOT assert a greenfield opportunity on an unverified basis.
                website_status = "NO_WEBSITE_UNVERIFIED"
                evidence_list.append({
                    "claim": "Official Website Status",
                    "value": "NO_WEBSITE_UNVERIFIED",
                    "evidence_level": "E3_INFERRED",
                    "source": candidate.get("source", "OpenStreetMap (Overpass API) public open data"),
                    "source_url": candidate.get("google_maps_url"),
                    "observed_at": now_str,
                    "notes": (
                        f"No website URL in the source record{social_note}, and the live web "
                        f"search could not be completed. This is NOT proof the business lacks a "
                        f"website -- it must be confirmed manually before pitching."
                    ),
                })
        else:
            # Real website fetch and analysis
            try:
                website_analysis = self.website_analyzer.analyze(raw_web)
                website_audit = website_analysis

                # Determine evidence-backed status.
                # An explicit mapping is required: any unrecognised status used to
                # collapse into FETCH_FAILED, which made a deliberately SSRF-blocked
                # URL (FETCH_BLOCKED) and a malformed URL (INVALID_URL)
                # indistinguishable from a website that was genuinely unreachable.
                fetch_status = website_analysis.get("fetch_status", "FETCH_FAILED")
                if fetch_status == "FETCH_OK":
                    website_status = "HTTPS_LIVE" if website_analysis.get("https") else "LIVE"
                else:
                    website_status = fetch_status

                # Add website evidence rows
                evidence_list.extend(self._build_website_evidence(website_analysis, now_str))

            except Exception as e:
                # Fallback to a no-assertion audit if website analysis fails
                website_status, website_audit = self._audit_website(raw_web)
                evidence_list.append({
                    "claim": "Website Analysis Error",
                    "value": type(e).__name__,
                    "evidence_level": "E4_UNCERTAIN",
                    "source": "Website Analyzer",
                    "source_url": raw_web,
                    "observed_at": now_str,
                    "notes": (
                        f"Website analysis could not complete ({type(e).__name__}). No automated "
                        f"website assessment was produced for {raw_web}. This URL must be reviewed "
                        f"manually; no modernization claims can be made from this record."
                    )
                })

            # Always add the original website audit evidence
            evidence_list.append({
                "claim": "Official Website Audit",
                "value": website_status,
                "evidence_level": "E1_DIRECT" if website_status == "ANALYSIS_UNAVAILABLE" else "E2_STRONG",
                "source": "Live HTTP fetch by Website Analyzer",
                "source_url": raw_web,
                "observed_at": now_str,
                "notes": (
                    f"Website inspection result for {raw_web}: {website_status}. "
                    + ("No measurements were taken." if website_status == "ANALYSIS_UNAVAILABLE"
                       else "Status derived from the live HTTP response.")
                )
            })

        # 4. WhatsApp Verification & Normalization
        raw_phone = candidate.get("phone", "")
        norm_phone, wa_number, wa_status = self._verify_whatsapp(raw_phone)

        # Upgrade to CONFIRMED only when the business ADVERTISES a WhatsApp link
        # online whose number matches this phone -- a genuine signal, unlike the
        # format-only guess. Otherwise the status stays explicitly unconfirmed.
        wa_confirmed = bool(presence and presence.get("whatsapp_confirmed") and presence.get("whatsapp_match"))
        if wa_confirmed:
            wa_status = "WHATSAPP_CONFIRMED"
        elif wa_status == "WHATSAPP_POSSIBLE":
            wa_status = "WHATSAPP_FORMAT_ONLY"  # honest: valid mobile shape, NOT verified

        if wa_confirmed:
            evidence_list.append({
                "claim": "WhatsApp Channel (confirmed)",
                "value": f"WHATSAPP_CONFIRMED ({wa_number})",
                "evidence_level": "E2_STRONG",
                "source": "Live web search (Bing) -- advertised wa.me link",
                "source_url": f"https://wa.me/{wa_number}" if wa_number else None,
                "observed_at": now_str,
                "notes": (
                    f"A WhatsApp link advertised online matches this number ({norm_phone}). "
                    f"This is an evidence-backed WhatsApp channel."
                ),
            })
        else:
            evidence_list.append({
                "claim": "WhatsApp Number Format Analysis",
                "value": f"{wa_status} ({wa_number or 'N/A'})",
                "evidence_level": "E3_INFERRED",
                "source": "Local number-pattern inference (no WhatsApp account check confirmed it)",
                "source_url": f"https://wa.me/{wa_number}" if wa_number else None,
                "observed_at": now_str,
                "notes": (
                    f"Phone normalized to {norm_phone}. Status {wa_status} means the number only "
                    f"MATCHES a WhatsApp-capable mobile shape. No confirmed WhatsApp account was "
                    f"found for it, so it is NOT verified -- confirm manually before messaging."
                ),
            })

        verified_data = {
            **candidate,
            "website_status": website_status,
            "website_audit": website_audit,
            "website_analysis": website_analysis,
            "phone_normalized": norm_phone,
            "whatsapp_number": wa_number,
            "whatsapp_status": wa_status,
            # True ONLY when a live search found an advertised WhatsApp link that
            # matches this number. Format-only numbers stay False and are labelled
            # "format-only / unverified" everywhere they surface.
            "whatsapp_verified": wa_confirmed,
            "whatsapp_confidence": "CONFIRMED" if wa_confirmed else "UNVERIFIED",
            "website_found_url": (presence or {}).get("website_found"),
            "is_shariah_compliant": True
        }

        return verified_data, evidence_list

    def _build_website_evidence(self, analysis: Dict[str, Any], now_str: str) -> List[Dict[str, Any]]:
        """Build evidence records from website analysis results."""
        evidence = []
        source_url = analysis.get("final_url") or analysis.get("source_url", "")

        # HTTP Status
        if analysis.get("http_status"):
            evidence.append({
                "claim": "HTTP Status",
                "value": str(analysis["http_status"]),
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"HTTP status code: {analysis['http_status']}"
            })

        # Final URL
        if analysis.get("final_url") and analysis["final_url"] != analysis.get("source_url"):
            evidence.append({
                "claim": "Final URL",
                "value": analysis["final_url"],
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": analysis["final_url"],
                "observed_at": now_str,
                "notes": f"Redirected from {analysis.get('source_url')} to {analysis['final_url']}"
            })

        # Page Title
        if analysis.get("title"):
            evidence.append({
                "claim": "Page Title",
                "value": analysis["title"],
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"Page title: {analysis['title']}"
            })

        # Meta Description
        if analysis.get("meta_description"):
            evidence.append({
                "claim": "Meta Description",
                "value": analysis["meta_description"],
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"Meta description: {analysis['meta_description']}"
            })

        # H1
        if analysis.get("h1"):
            evidence.append({
                "claim": "H1 Heading",
                "value": " | ".join(analysis["h1"][:3]),
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"H1 headings found: {len(analysis['h1'])}"
            })

        # WhatsApp Link
        if analysis.get("whatsapp_links"):
            evidence.append({
                "claim": "WhatsApp Link",
                "value": analysis["whatsapp_links"][0],
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": analysis["whatsapp_links"][0],
                "observed_at": now_str,
                "notes": f"WhatsApp link found: {analysis['whatsapp_links'][0]}"
            })

        # Contact Page
        if analysis.get("contact_page_detected"):
            evidence.append({
                "claim": "Contact Page Detected",
                "value": "Yes",
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": "Contact page link detected in HTML"
            })

        # Booking Page
        if analysis.get("booking_detected"):
            evidence.append({
                "claim": "Booking Page Detected",
                "value": "Yes",
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": "Booking/appointment page link detected"
            })

        # Ordering Page
        if analysis.get("ordering_detected"):
            evidence.append({
                "claim": "Ordering Page Detected",
                "value": "Yes",
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": "Ordering/menu page link detected"
            })

        # HTTPS
        if analysis.get("https"):
            evidence.append({
                "claim": "HTTPS",
                "value": "Yes",
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": "Website uses HTTPS"
            })

        # Response Time
        if analysis.get("response_time_ms"):
            evidence.append({
                "claim": "Response Time",
                "value": f"{analysis['response_time_ms']}ms",
                "evidence_level": "E1_DIRECT",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"Response time: {analysis['response_time_ms']}ms"
            })

        # Opportunity Signals
        for signal in analysis.get("opportunity_signals", []):
            evidence.append({
                "claim": f"Signal: {signal['signal']}",
                "value": signal["evidence"],
                "evidence_level": "E2_STRONG",
                "source": source_url,
                "source_url": source_url,
                "observed_at": now_str,
                "notes": f"Severity: {signal['severity']}"
            })

        return evidence

    def _verify_whatsapp(self, raw_phone: str) -> Tuple[str, str, str]:
        """
        Normalise a phone number and report whether its FORMAT matches a
        WhatsApp-capable mobile range.

        IMPORTANT: no WhatsApp verification mechanism is called here. The status
        returned describes the number's shape only. A number that matches a mobile
        range may still have no WhatsApp account registered against it, so this
        method deliberately never returns a "verified" status -- the strongest
        outcome it can honestly report is WHATSAPP_POSSIBLE (format match).
        """
        if not raw_phone:
            return "", "", "UNKNOWN"

        digits = re.sub(r'\D', '', raw_phone)
        if len(digits) < 7:
            return raw_phone, "", "UNKNOWN"

        # Check Pakistan Numbers (03xx or 923xx)
        if digits.startswith("923") and len(digits) == 12:
            return f"+{digits[:2]} {digits[2:5]} {digits[5:]}", digits, "WHATSAPP_POSSIBLE"
        if digits.startswith("03") and len(digits) == 11:
            clean = "92" + digits[1:]
            return f"+92 {digits[1:4]} {digits[4:]}", clean, "WHATSAPP_POSSIBLE"
        if digits.startswith("3") and len(digits) == 10:
            clean = "92" + digits
            return f"+92 {digits[:3]} {digits[3:]}", clean, "WHATSAPP_POSSIBLE"

        # Check UK Numbers (07xxx or 447xxx)
        if digits.startswith("447") and len(digits) == 12:
            return f"+{digits[:2]} {digits[2:6]} {digits[6:]}", digits, "WHATSAPP_POSSIBLE"
        if digits.startswith("07") and len(digits) == 11:
            clean = "44" + digits[1:]
            return f"+44 {digits[1:5]} {digits[5:]}", clean, "WHATSAPP_POSSIBLE"

        # General International Mobile
        if len(digits) >= 10:
            return f"+{digits}", digits, "WHATSAPP_POSSIBLE"

        return raw_phone, "", "PHONE_ONLY"

    def _audit_website(self, url: str) -> Tuple[str, Dict[str, Any]]:
        """
        Fallback audit used only when WebsiteAnalyzer.analyze() raises.

        This performs NO network inspection, so it must not assert any measured
        weakness (HTTPS state, responsiveness, load time, broken links). It reports
        an honest "not assessed" result and leaves the weaknesses list empty rather
        than inventing findings from a URL substring match.
        """
        return "ANALYSIS_UNAVAILABLE", {
            "weakness_score": None,
            "issues": [],
            "modernization_urgency": "UNKNOWN",
            "recommended_action": (
                "Re-run website analysis manually before making any modernization claim. "
                "No automated assessment was completed for this URL."
            ),
            "assessed": False,
            "assessment_note": (
                "No website measurements were taken. This record contains no findings "
                "because none were gathered, not because the site was found to be sound."
            )
        }
